# Statistical tests

This Notebook contains code that will repeat the statistical tests that attempted to identify any relationship between endolichenic fungal isolates and their host lichens.

In [80]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

## Pearson's Chi-Squared tests 

A Pearson's Chi-Squared test is commonly used for comparing large categorical datasets.

The folowing code is testing the hypothesis that each of the taxonomic levels of endolichenic fungi are not related to one another.

In [81]:
data = pd.read_csv("../ELF_master_results.csv")
data_sub = pd.DataFrame()
data.fillna("unidentified", inplace=True)
data_sub["isolate_class"] = data["isolate_class"].astype("category").cat.codes
data_sub["isolate_order"] = data["isolate_order"].astype("category").cat.codes
data_sub["isolate_family"] = data["isolate_family"].astype("category").cat.codes
data_sub["isolate_genus"] = data["isolate_genus"].astype("category").cat.codes
data_sub["Host_ID"] = data["Host_ID"].astype("category").cat.codes
data_sub["Host_location"] = data["Host_location"].astype("category").cat.codes
data_sub["Host_Order"] = data["Host_Order"].astype("category").cat.codes
data_sub["Host_Family"] = data["Host_Family"].astype("category").cat.codes
data_sub["Host_Genus"] = data["Host_Genus"].astype("category").cat.codes
data_sub["Host_Species"] = data["Host_Species"].astype("category").cat.codes
data_sub["Photobiont"] = data["Photobiont"].astype("category").cat.codes
data_sub["Growth_form"] = data["Growth_form"].astype("category").cat.codes
data_sub["Macroclimate"] = data["Macroclimate"].astype("category").cat.codes

data_sub.head()

isolate_class  isolate_order  isolate_family  isolate_genus  Host_ID  \
0              7              6              14             62        9   
1              4              8              17             31        9   
2              4              8              17             31        9   
3             10             21              45             67        9   
4              4              8              17             31        9   

   Host_location  Host_Order  Host_Family  Host_Genus  Host_Species  \
0              2           2            5          14             5   
1              2           2            5          14             5   
2              2           2            5          14             5   
3              2           2            5          14             5   
4              2           2            5          14             5   

   Photobiont  Growth_form  Macroclimate  
0           0            1             6  
1           0            1             6  
2           0            1             6  
3           0            1             6  
4           0            1             6

In [82]:
def pearsons_chi2(df, var1, var2):
    crosstab = pd.crosstab(df[var1], df[var2])
    stat, p, dof, expected = chi2_contingency(crosstab)

    diction = {"Variables": f"{var1}_vs_{var2}",
                "Chi-Squared Statistic": stat, 
                "p-value": p,
                "Degrees of Freedom": dof}
    dict_df = pd.DataFrame(data=diction, index=[0])
    #final_df = pd.concat([final_df, dict_df], ignore_index=True)
    #final_df = final_df.append(dict_df)
    #print(final_df)
    
    print("Chi-Squared Statistic: ", stat)
    print("p-value: ", p)
    print("Degrees of Freedom: ", dof)
    print("Expected Values: ", expected)

    return dict_df

The below will prepare a list of tuples containing each of the elements of isolate and host variable lists, then apply these to the `pearsons_chi2` function.

In [83]:
final_dataframe = pd.DataFrame()

isolate_vars = ["isolate_genus", "isolate_family", "isolate_order", "isolate_class"]
host_vars = ["Host_Species", "Host_Genus", "Host_Family", "Host_Order",
    "Host_location", "Photobiont", "Growth_form", "Macroclimate",]
result = [(x, y) for x in isolate_vars for y in host_vars]

for i in result:
    df = pearsons_chi2(data_sub, i[0], i[1])
    final_dataframe = pd.concat([final_dataframe, df], ignore_index=True)

Chi-Squared Statistic:  2669.7408788418043
p-value:  1.6103986335199512e-21
Degrees of Freedom:  2010
Expected Values:  [[0.02894737 0.00789474 0.04473684 ... 0.01052632 0.01578947 0.01578947]
 [0.28947368 0.07894737 0.44736842 ... 0.10526316 0.15789474 0.15789474]
 [0.43421053 0.11842105 0.67105263 ... 0.15789474 0.23684211 0.23684211]
 ...
 [0.26052632 0.07105263 0.40263158 ... 0.09473684 0.14210526 0.14210526]
 [0.05789474 0.01578947 0.08947368 ... 0.02105263 0.03157895 0.03157895]
 [2.51842105 0.68684211 3.89210526 ... 0.91578947 1.37368421 1.37368421]]
Chi-Squared Statistic:  2436.705483184971
p-value:  4.14612591917959e-37
Degrees of Freedom:  1608
Expected Values:  [[1.84210526e-02 3.68421053e-02 5.26315789e-03 ... 1.57894737e-02
  7.36842105e-02 1.57894737e-02]
 [1.84210526e-01 3.68421053e-01 5.26315789e-02 ... 1.57894737e-01
  7.36842105e-01 1.57894737e-01]
 [2.76315789e-01 5.52631579e-01 7.89473684e-02 ... 2.36842105e-01
  1.10526316e+00 2.36842105e-01]
 ...
 [1.65789474e-01 

In [84]:
final_df.to_csv("pearsons_chi_squared_tests.csv")
display(final_dataframe)

Variables  Chi-Squared Statistic       p-value  \
0     isolate_genus_vs_Host_Species            2669.740879  1.610399e-21   
1       isolate_genus_vs_Host_Genus            2436.705483  4.146126e-37   
2      isolate_genus_vs_Host_Family            1345.802843  2.695727e-12   
3       isolate_genus_vs_Host_Order             468.031615  1.269443e-02   
4    isolate_genus_vs_Host_location            2051.395460  2.822886e-13   
5       isolate_genus_vs_Photobiont             344.841687  1.054765e-03   
6      isolate_genus_vs_Growth_form             140.462160  3.339095e-01   
7     isolate_genus_vs_Macroclimate             692.800731  7.253408e-11   
8    isolate_family_vs_Host_Species            1878.458525  4.735137e-20   
9      isolate_family_vs_Host_Genus            1694.618736  4.601834e-30   
10    isolate_family_vs_Host_Family             987.039765  4.005536e-14   
11     isolate_family_vs_Host_Order             329.470579  7.750014e-03   
12  isolate_family_vs_Host_location            1543.406929  5.001811e-19   
13     isolate_family_vs_Photobiont             260.915935  7.593863e-05   
14    isolate_family_vs_Growth_form              97.822895  2.688268e-01   
15   isolate_family_vs_Macroclimate             559.651441  6.190149e-16   
16    isolate_order_vs_Host_Species            1067.179417  4.740187e-25   
17      isolate_order_vs_Host_Genus             935.596336  2.786112e-28   
18     isolate_order_vs_Host_Family             584.303792  2.220417e-18   
19      isolate_order_vs_Host_Order             239.916758  4.103976e-09   
20   isolate_order_vs_Host_location             873.965627  2.728949e-22   
21      isolate_order_vs_Photobiont             159.593588  1.271176e-06   
22     isolate_order_vs_Growth_form              56.570353  6.591474e-02   
23    isolate_order_vs_Macroclimate             353.460485  4.849226e-19   
24    isolate_class_vs_Host_Species             494.892796  9.489467e-12   
25      isolate_class_vs_Host_Genus             420.776659  4.776819e-12   
26     isolate_class_vs_Host_Family             237.331625  7.156065e-06   
27      isolate_class_vs_Host_Order             116.994482  1.513523e-05   
28   isolate_class_vs_Host_location             456.764716  1.161455e-15   
29      isolate_class_vs_Photobiont              56.700175  4.191290e-02   
30     isolate_class_vs_Growth_form              29.802098  7.312447e-02   
31    isolate_class_vs_Macroclimate             222.016618  1.042432e-17   

    Degrees of Freedom  
0                 2010  
1                 1608  
2                 1005  
3                  402  
4                 1608  
5                  268  
6                  134  
7                  469  
8                 1350  
9                 1080  
10                 675  
11                 270  
12                1080  
13                 180  
14                  90  
15                 315  
16                 630  
17                 504  
18                 315  
19                 126  
20                 504  
21                  84  
22                  42  
23                 147  
24                 300  
25                 240  
26                 150  
27                  60  
28                 240  
29                  40  
30                  20  
31                  70

## Prepare data for rarefaction curves on iNEXT

The following text will prepare abundance stats which can be input into the [iNEXT](https://chao.shinyapps.io/iNEXTOnline/) online viewer to generate rarefaction curves of endolichenic fungi genera diversity against lichen host Order.

http://chao.stat.nthu.edu.tw/wordpress/wp-content/uploads/software/iNEXTOnline_UserGuide.pdf

In [85]:
data_sub2 = pd.DataFrame()
data_sub2["isolate_genus"] = data["isolate_genus"]
data_sub2["Host_Order"] = data["Host_Order"]
results = pd.crosstab(data_sub2['isolate_genus'], data_sub2['Host_Order'])

In [87]:
results.to_cvs("iNEXT_input.csv")
display(results)

Host_Order         Gyalectales  Lecanorales  Peltigerales  Pertusariales  \
isolate_genus                                                              
Absidia                      0            0             0              0   
Amphirosellinia              0            6             4              0   
Anthostomelloides            2            6             5              2   
Antrelloides                 0            1             0              0   
Ascochyta                    0            2             0              0   
...                        ...          ...           ...            ...   
Trichonectria                0            1             0              0   
Umbelopsis                   0            3             1              0   
Xylaria                      0            5             3              1   
Xylotumulus                  0            2             0              0   
unidentified                 0           29            43              4   

Host_Order         Teloschistales  Trichotheliales  unidentified  
isolate_genus                                                     
Absidia                         0                1             0  
Amphirosellinia                 0                0             0  
Anthostomelloides               0                0             0  
Antrelloides                    0                0             0  
Ascochyta                       0                0             0  
...                           ...              ...           ...  
Trichonectria                   0                0             0  
Umbelopsis                      0                0             0  
Xylaria                         0                0             0  
Xylotumulus                     0                0             0  
unidentified                    8                3             0  

[68 rows x 7 columns]